In [28]:
import pandas as pd
import numpy as np
import pycaret
from pycaret.classification import load_model

# Load the data
# challenge_abtier_processed_nov11.csv  challenge_cell_freq_processed_nov11.csv  challenge_t_cell_processed_task4.1_nov11.csv
task1 = pd.read_csv('/home/vmottaqi/cmipb_challenge/vincent_files/challenge_abtier_processed_nov17.csv', index_col=0)
task2 = pd.read_csv('/home/vmottaqi/cmipb_challenge/vincent_files/challenge_cell_freq_processed_nov17.csv', index_col=0)
task4 = pd.read_csv('/home/vmottaqi/cmipb_challenge/vincent_files/challenge_t_cell_processed_task4.1_nov17.csv', index_col=0)

# sort df by specimen_id
task1 = task1.sort_values('subject_id')
task2 = task2.sort_values('subject_id')
task4 = task4.sort_values('subject_id')

# Load submission template
submission = pd.read_csv('/home/jrollins/cmipb-challenge/3rdChallengeSubmissionTemplate_10032024.tsv', sep='\t')

# Task 1

In [29]:
# Load a pycaret model /home/jrollins/cmipb-challenge/task1-2_best_scc_model.pkl
from pycaret.classification import load_model
model = load_model('/home/jrollins/cmipb-challenge/task1-2_best_scc_model')

# Use the model to make predictions
predictions = model.predict(task1)

Transformation Pipeline and Model Successfully Loaded

In [30]:
predictions

array([ 4.13613046,  5.12220753,  5.12220753,  3.81403777,  3.63480969,
        5.12220753,  8.1306395 ,  5.79992039,  5.29812048,  5.29812048,
        6.03724065,  4.42372201,  5.12220753,  5.12220753,  4.75162032,
        8.75900523,  8.1306395 ,  8.1306395 ,  5.12220753,  4.75162032,
        6.15864605,  5.12220753,  5.29812048, 13.36439498,  5.01416908,
        4.75162032,  8.54543644,  5.01416908,  5.01416908,  6.94161658,
        5.01416908,  5.98204477, 12.95479202,  5.79992039,  5.29812048,
        8.48193555,  4.75162032,  3.55666759,  4.75162032,  3.63480969,
        5.29812048,  5.29812048,  5.98204477,  5.12220753, 14.85203389,
        8.48193555,  5.79992039,  5.12220753,  8.54543644,  5.12220753,
        7.39080232,  6.03724065,  5.79992039,  8.48193555])

In [31]:
# Multiply predictions by day_0_IgG_PT for Day 14 predictions without fold change
task11_pred = predictions * task1['day_0_IgG_PT']

In [32]:
task11_pred = task11_pred.to_list()

In [33]:
task11_pred

[6.465939687623806,
 7.730979888432682,
 3.7441516948463107,
 7.150514121027797,
 8.081455052806653,
 3.1547944836205044,
 8.25445634087098,
 5.790106645457071,
 3.5141509760066376,
 5.9884001325827585,
 4.290424830417341,
 5.179721876284344,
 3.2241306261176557,
 7.765647959681226,
 5.547577022862001,
 3.9126520828903146,
 4.842614386644305,
 5.860664002018394,
 3.709483623597735,
 6.303333892643216,
 4.2933370120092205,
 3.7441516948463107,
 5.127791730295395,
 5.698523748949694,
 5.820169185635524,
 53.642657821065406,
 3.123205195363263,
 68.84089325400382,
 18.597391916782954,
 6.005125889492961,
 21.27840279529731,
 11.538969612253583,
 4.864803680292585,
 7.243850495423682,
 4.231324644579419,
 3.961106959207683,
 4.4410137062016295,
 7.143015301249683,
 6.595434045817317,
 7.320173066801987,
 4.5096658298579095,
 28.48752957227235,
 7.288277080469331,
 5.286061175267215,
 4.048676831665896,
 13.566378146104181,
 6.0338531966335145,
 3.476546972412929,
 2.6622778330433827,
 12.011184826820067,
 3.9472435193106374,
 4.265533035255772,
 3.48479222051563,
 6.771392222490266]

In [34]:
len(predictions)

54

In [35]:
# rank the task 1.1 predictions 1 to 54 with the highest as 1
pred_rank_11 = np.argsort(task11_pred) + 1
# rank the task 1.2 predictions 1 to 54 with the highest as 1
pred_rank_12 = np.argsort(predictions) + 1

In [36]:
pred_rank_11

array([49, 27,  6, 13, 48, 53,  9, 19,  3, 22, 16, 51, 36, 45, 35, 52, 11,
       21, 37, 41, 17, 33, 23, 12, 44, 15, 24,  8, 25, 18, 10, 30, 47, 20,
        1, 39, 54, 38,  4, 34, 43, 40,  2, 14,  5,  7, 32, 50, 46, 29, 31,
       42, 26, 28])

In [37]:
pred_rank_12

array([38,  5, 40,  4,  1, 12, 26, 20, 37, 39, 15, 25, 31, 28, 29, 13, 48,
       19, 50, 22, 44,  6,  3,  2, 14, 41, 35, 42, 23, 10,  9, 34,  8, 53,
       47, 32, 43, 52, 11, 21, 30, 51, 18, 17,  7, 54, 36, 46, 49, 27, 16,
       33, 24, 45])

In [38]:
# Load submission template from tsv
submission['1.1) IgG-PT-D14-titer-Rank'] = pred_rank_11
submission['1.2) IgG-PT-D14-FC-Rank'] = pred_rank_12

# Task 2

In [39]:
# load /home/jrollins/cmipb-challenge/task2-1_best_scc_model.pkl
from pycaret.classification import load_model
model = load_model('/home/jrollins/cmipb-challenge/task2-1_best_scc_model')


# Use the model to make predictions
predictions = model.predict(task2)

Transformation Pipeline and Model Successfully Loaded

In [40]:
predictions

array([1.12471939, 1.06664901, 0.97899171, 1.1177591 , 1.78091849,
       1.03236523, 0.88989945, 1.35573825, 1.52231882, 0.98122975,
       1.16296816, 1.57414494, 1.60477786, 1.09896365, 1.35414083,
       1.02407204, 1.59281168, 0.90996071, 1.06115233, 1.45652369,
       1.11700076, 1.22621026, 1.09348078, 1.08802925, 1.08754136,
       1.00895593, 1.23378746, 1.01450573, 1.29056003, 1.36141176,
       1.21476027, 1.0167408 , 1.06025463, 0.97765548, 1.08412518,
       1.24213878, 1.388357  , 1.11906547, 1.37043859, 1.39410787,
       0.91707047, 0.87328052, 0.89671061, 0.92995603, 1.52659922,
       1.41636244, 0.97956671, 1.0567777 , 1.16679192, 1.21431731,
       1.40663338, 1.45689556, 1.05320411, 1.15605615])

In [41]:
pred_rank_21 = np.argsort(predictions) + 1

In [42]:
pred_rank_21

array([42,  7, 43, 18, 41, 44, 34,  3, 47, 10, 26, 28, 32, 16,  6, 53, 48,
       33, 19,  2, 35, 25, 24, 23, 14, 21,  4, 38,  1, 54, 11, 49, 50, 31,
       22, 27, 36, 29, 15,  8, 30, 39, 37, 40, 51, 46, 20, 52,  9, 45, 12,
       17, 13,  5])

In [43]:
pred22 = predictions/task2['day_0_Monocytes']

In [44]:
pred22

5     1.066669
10    2.425492
13    1.494711
14    1.130987
7     1.140588
16    1.412276
17    1.777720
18    0.986516
15    1.049663
19    1.190002
2     1.176731
9     0.789381
21    0.868408
22    1.167222
23    0.922542
24    1.074333
20    0.794084
8     1.215651
25    1.099740
27    1.163858
3     0.984573
29    1.219081
6          NaN
31         NaN
28    1.215487
32    1.307057
33    1.263339
34    1.112054
35    1.120232
12    0.971493
26         NaN
30    1.136357
36         NaN
37    1.026538
38         NaN
39    1.062029
40    0.953684
41         NaN
42    0.757348
43    1.090074
44    0.976879
11    1.473849
45    1.522130
4     1.168406
47    1.144949
48    1.293200
46    1.099208
49    1.159301
50    1.099477
51    1.056240
52    1.039071
0     1.024706
53    0.955685
1     1.452481
Name: day_0_Monocytes, dtype: float64

In [45]:
pred_rank_22 = np.argsort(pred22) + 1

In [46]:
pred_rank_22

5     33
10    12
13    17
14    13
7     15
16    32
17    47
18    28
15    35
19    21
2      8
9     46
21    30
22    45
23     9
24    44
20    31
8      1
25    16
27    34
3     41
29    43
6      0
31     0
28    19
32    26
33    27
34     4
35    29
12     5
26     0
30    39
36     0
37    42
38     0
39    20
40    14
41     0
42    38
43    11
44    10
11    23
45    18
4     22
47    25
48    40
46    24
49     6
50    48
51    36
52     3
0     37
53     7
1      2
Name: day_0_Monocytes, dtype: int64

In [47]:
# replace NaN with 'NA'
pred_rank_22 = np.where('0', 'NA', pred_rank_22)
pred_rank_22

array(['33', '12', '17', '13', '15', '32', '47', '28', '35', '21', '8',
       '46', '30', '45', '9', '44', '31', '1', '16', '34', '41', '43',
       '0', '0', '19', '26', '27', '4', '29', '5', '0', '39', '0', '42',
       '0', '20', '14', '0', '38', '11', '10', '23', '18', '22', '25',
       '40', '24', '6', '48', '36', '3', '37', '7', '2'], dtype='<U21')

In [48]:
# make all the strings ints for pred_rank_22
pred_rank_22 = pred_rank_22.astype(int)

In [49]:
pred_rank_22

array([33, 12, 17, 13, 15, 32, 47, 28, 35, 21,  8, 46, 30, 45,  9, 44, 31,
        1, 16, 34, 41, 43,  0,  0, 19, 26, 27,  4, 29,  5,  0, 39,  0, 42,
        0, 20, 14,  0, 38, 11, 10, 23, 18, 22, 25, 40, 24,  6, 48, 36,  3,
       37,  7,  2])

In [50]:
pred_rank_21
pred_rank_22

array([33, 12, 17, 13, 15, 32, 47, 28, 35, 21,  8, 46, 30, 45,  9, 44, 31,
        1, 16, 34, 41, 43,  0,  0, 19, 26, 27,  4, 29,  5,  0, 39,  0, 42,
        0, 20, 14,  0, 38, 11, 10, 23, 18, 22, 25, 40, 24,  6, 48, 36,  3,
       37,  7,  2])

In [51]:
submission['2.1) Monocytes-D1-Rank'] = pred_rank_21
submission['2.2) Monocytes-D1-FC-Rank'] = pred_rank_22

In [52]:
submission

,SubjectID,Age,BiologicalSexAtBirth,VaccinePrimingStatus,1.1) IgG-PT-D14-titer-Rank,1.2) IgG-PT-D14-FC-Rank,2.1) Monocytes-D1-Rank,2.2) Monocytes-D1-FC-Rank,3.1) CCL3-D3-Rank,3.2) CCL3-D3-FC-Rank,4.1) IFNG/IL5-Polarization-D30-Rank
0,119,23,Female,aP,49,38,42,33,NaN,NaN,NaN
1,120,27,Female,wP,27,5,7,12,NaN,NaN,NaN
2,121,22,Female,aP,6,40,43,17,NaN,NaN,NaN
3,122,23,Female,aP,13,4,18,13,NaN,NaN,NaN
4,123,26,Female,wP,48,1,41,15,NaN,NaN,NaN
5,124,22,Male,aP,53,12,44,32,NaN,NaN,NaN
6,125,29,Male,wP,9,26,34,47,NaN,NaN,NaN
7,126,29,Male,wP,19,20,3,28,NaN,NaN,NaN
8,127,26,Female,aP,3,37,47,35,NaN,NaN,NaN
9,128,28,Female,wP,22,39,10,21,NaN,NaN,NaN
10,129,31,Male,wP,16,15,26,8,NaN,NaN,NaN
11,130,26,Male,wP,51,25,28,46,NaN,NaN,NaN
12,131,24,Female,aP,36,31,32,30,NaN,NaN,NaN
13,132,27,Male,wP,45,28,16,45,NaN,NaN,NaN
14,133,25,Female,aP,35,29,6,9,NaN,NaN,NaN
15,134,32,Male,wP,52,13,53,44,NaN,NaN,NaN
16,135,27,Male,wP,11,48,48,31,NaN,NaN,NaN
17,136,27,Female,wP,21,19,33,1,NaN,NaN,NaN
18,137,24,Female,aP,37,50,19,16,NaN,NaN,NaN
19,138,22,Male,aP,41,22,2,34,NaN,NaN,NaN
20,139,29,Female,wP,17,44,35,41,NaN,NaN,NaN
21,140,21,Female,aP,33,6,25,43,NaN,NaN,NaN
22,141,26,Female,wP,23,3,24,0,NaN,NaN,NaN
23,142,31,Female,aP,12,2,23,0,NaN,NaN,NaN
24,143,19,Female,aP,44,14,14,19,NaN,NaN,NaN
25,144,23,Female,aP,15,41,21,26,NaN,NaN,NaN
26,145,20,Male,aP,24,35,4,27,NaN,NaN,NaN
27,146,31,Male,wP,8,42,38,4,NaN,NaN,NaN
28,147,23,Female,aP,25,23,1,29,NaN,NaN,NaN
29,148,35,Male,wP,18,10,54,5,NaN,NaN,NaN
30,149,32,Female,wP,10,9,11,0,NaN,NaN,NaN
31,150,32,Male,wP,30,34,49,39,NaN,NaN,NaN
32,151,31,Female,wP,47,8,50,0,NaN,NaN,NaN
33,152,28,Female,wP,20,53,31,42,NaN,NaN,NaN
34,153,25,Female,aP,1,47,22,0,NaN,NaN,NaN
35,154,26,Female,aP,39,32,27,20,NaN,NaN,NaN
36,155,26,Female,aP,54,43,36,14,NaN,NaN,NaN
37,156,22,Female,aP,38,52,29,0,NaN,NaN,NaN
38,157,26,Female,aP,4,11,15,38,NaN,NaN,NaN
39,158,23,Male,aP,34,21,8,11,NaN,NaN,NaN
40,159,29,Female,wP,43,30,30,10,NaN,NaN,NaN
41,160,27,Male,aP,40,51,39,23,NaN,NaN,NaN
42,161,30,Female,aP,2,18,37,18,NaN,NaN,NaN
43,162,24,Female,aP,14,17,40,22,NaN,NaN,NaN
44,163,30,Female,wP,5,7,51,25,NaN,NaN,NaN
45,164,32,Male,wP,7,54,46,40,NaN,NaN,NaN
46,165,30,Female,wP,32,36,20,24,NaN,NaN,NaN
47,166,22,Female,aP,50,46,52,6,NaN,NaN,NaN
48,167,26,Male,aP,46,49,9,48,NaN,NaN,NaN
49,168,32,Male,wP,29,27,45,36,NaN,NaN,NaN
50,169,20,Male,aP,31,16,12,3,NaN,NaN,NaN
51,170,31,Male,wP,42,33,17,37,NaN,NaN,NaN
52,171,20,Female,wP,26,24,13,7,NaN,NaN,NaN
53,172,36,Male,wP,28,45,5,2,NaN,NaN,NaN

# Task 4.1

In [53]:
# Load the Task 4.1 model
model41_th1 = load_model('/home/jrollins/cmipb-challenge/Th1_model_11102024_58scc')
model41_th2 = load_model('/home/jrollins/cmipb-challenge/Th2_model_11102024_58scc')

Transformation Pipeline and Model Successfully Loaded
Transformation Pipeline and Model Successfully Loaded

In [54]:
# get predictions for task 4.1
sel_feat = ['day_0_Th2_PHA', 'day_0_IL17A_PT', 'biological_sex', 'day_0_Th2_PT', 'day_0_IL17A_PHA', 'day_0_Th1_PHA', 'day_0_Th1_PT', 'age', 'infancy_vac']
X_41 = task4[sel_feat]

In [55]:
predictions_th1 = model41_th1.predict(X_41)
predictions_th2 = model41_th2.predict(X_41)

In [56]:
merg = predictions_th1/predictions_th2

In [57]:
merg

array([2.97226718, 3.61416494, 0.6748692 , 2.19447898, 0.36251466,
       0.4997714 , 0.59778225, 1.57001135, 2.75859539, 2.05644499,
       0.32655264, 1.65596645, 2.30643444, 0.32785299, 6.95307584,
       0.50805914, 1.64662739, 2.76977985, 3.59526218, 1.21071524,
       1.03999061, 7.08476887, 0.30304986, 2.54290107, 0.54504117,
       4.06021087, 7.94046247, 0.43990505, 1.627209  , 1.31886177,
       0.48110596, 1.00882876, 0.69268133, 0.51856136, 1.69044003,
       1.48417826, 2.54838655, 0.56324551, 0.5141629 , 0.56403655,
       2.18331661, 1.65935876, 0.43471028, 0.55192692, 2.33565363,
       0.43140522, 1.56258586, 3.36798581, 0.50669716, 0.81702494,
       0.5041422 , 0.94799066, 3.26155193, 0.82502218])

In [58]:
# rank the predictions 1 to 54 with the highest as 1
pred_rank_41 = np.argsort(merg) + 1

In [59]:
pred_rank_41

array([23, 11, 14,  5, 46, 43, 28, 31,  6, 51, 49, 16, 39, 34, 25, 44, 38,
       40,  7,  3, 33, 50, 54, 52, 32, 21, 20, 30, 36, 47,  8, 29, 17, 12,
       42, 35, 10, 41,  4, 13, 45, 24, 37,  9, 18,  1, 53, 48, 19,  2, 26,
       15, 22, 27])

In [60]:
submission['4.1) IFNG/IL5-Polarization-D30-Rank'] = pred_rank_41

In [61]:
# Fill all NaN with "NA"
submission = submission.fillna("NA")

In [62]:
submission

,SubjectID,Age,BiologicalSexAtBirth,VaccinePrimingStatus,1.1) IgG-PT-D14-titer-Rank,1.2) IgG-PT-D14-FC-Rank,2.1) Monocytes-D1-Rank,2.2) Monocytes-D1-FC-Rank,3.1) CCL3-D3-Rank,3.2) CCL3-D3-FC-Rank,4.1) IFNG/IL5-Polarization-D30-Rank
0,119,23,Female,aP,49,38,42,33,NA,NA,23
1,120,27,Female,wP,27,5,7,12,NA,NA,11
2,121,22,Female,aP,6,40,43,17,NA,NA,14
3,122,23,Female,aP,13,4,18,13,NA,NA,5
4,123,26,Female,wP,48,1,41,15,NA,NA,46
5,124,22,Male,aP,53,12,44,32,NA,NA,43
6,125,29,Male,wP,9,26,34,47,NA,NA,28
7,126,29,Male,wP,19,20,3,28,NA,NA,31
8,127,26,Female,aP,3,37,47,35,NA,NA,6
9,128,28,Female,wP,22,39,10,21,NA,NA,51
10,129,31,Male,wP,16,15,26,8,NA,NA,49
11,130,26,Male,wP,51,25,28,46,NA,NA,16
12,131,24,Female,aP,36,31,32,30,NA,NA,39
13,132,27,Male,wP,45,28,16,45,NA,NA,34
14,133,25,Female,aP,35,29,6,9,NA,NA,25
15,134,32,Male,wP,52,13,53,44,NA,NA,44
16,135,27,Male,wP,11,48,48,31,NA,NA,38
17,136,27,Female,wP,21,19,33,1,NA,NA,40
18,137,24,Female,aP,37,50,19,16,NA,NA,7
19,138,22,Male,aP,41,22,2,34,NA,NA,3
20,139,29,Female,wP,17,44,35,41,NA,NA,33
21,140,21,Female,aP,33,6,25,43,NA,NA,50
22,141,26,Female,wP,23,3,24,0,NA,NA,54
23,142,31,Female,aP,12,2,23,0,NA,NA,52
24,143,19,Female,aP,44,14,14,19,NA,NA,32
25,144,23,Female,aP,15,41,21,26,NA,NA,21
26,145,20,Male,aP,24,35,4,27,NA,NA,20
27,146,31,Male,wP,8,42,38,4,NA,NA,30
28,147,23,Female,aP,25,23,1,29,NA,NA,36
29,148,35,Male,wP,18,10,54,5,NA,NA,47
30,149,32,Female,wP,10,9,11,0,NA,NA,8
31,150,32,Male,wP,30,34,49,39,NA,NA,29
32,151,31,Female,wP,47,8,50,0,NA,NA,17
33,152,28,Female,wP,20,53,31,42,NA,NA,12
34,153,25,Female,aP,1,47,22,0,NA,NA,42
35,154,26,Female,aP,39,32,27,20,NA,NA,35
36,155,26,Female,aP,54,43,36,14,NA,NA,10
37,156,22,Female,aP,38,52,29,0,NA,NA,41
38,157,26,Female,aP,4,11,15,38,NA,NA,4
39,158,23,Male,aP,34,21,8,11,NA,NA,13
40,159,29,Female,wP,43,30,30,10,NA,NA,45
41,160,27,Male,aP,40,51,39,23,NA,NA,24
42,161,30,Female,aP,2,18,37,18,NA,NA,37
43,162,24,Female,aP,14,17,40,22,NA,NA,9
44,163,30,Female,wP,5,7,51,25,NA,NA,18
45,164,32,Male,wP,7,54,46,40,NA,NA,1
46,165,30,Female,wP,32,36,20,24,NA,NA,53
47,166,22,Female,aP,50,46,52,6,NA,NA,48
48,167,26,Male,aP,46,49,9,48,NA,NA,19
49,168,32,Male,wP,29,27,45,36,NA,NA,2
50,169,20,Male,aP,31,16,12,3,NA,NA,26
51,170,31,Male,wP,42,33,17,37,NA,NA,15
52,171,20,Female,wP,26,24,13,7,NA,NA,22
53,172,36,Male,wP,28,45,5,2,NA,NA,27

In [63]:
# save the submission to tsv
submission.to_csv('/home/jrollins/cmipb-challenge/Mottaqi_Rollins_3rdChallenge_final_11222024.tsv', sep='\t', index=False)